Fix path resolver when path start with directory separator
nunomaduro/phpinsights pull request #509
Opened 2021-06-22 16:16 UTC by 50bhan

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Fixed tickets | #508

This PR will close #508.

2021-07-04 09:10 UTC, Jibbarth requested changes
Hey @50bhan, just tested your implementation. 

Given PHPInsights is installed globally, I execute it from my HOME directory.

```
$ phpinsights analyse /tmp/app 
```
This work and launch the analyse on the expected directory

```
$ phpinsights analyse /tmp
```
This doesn't work, raise the following exception : 
```
  The "/home/barth/tmp" directory does not exist.  
```

So we have a regression here

2021-07-04 09:10 UTC, Jibbarth commented on tests/Application/PathResolverTest.php
> +        $sanitizedPath = getcwd() . $path;
I think it's incorrect. 

If I provide an absolute path (like `/app`), this shouldn't be resolved as `current working dir + app`.

2021-07-04 09:23 UTC, Jibbarth commented
@50bhan, for me, the bug is here https://github.com/nunomaduro/phpinsights/blob/master/src/Infrastructure/Repositories/LocalFilesRepository.php#L66

Could be resolved like this 

```php
$this->directoryList[] = rtrim($pathInfo['dirname'], DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . $pathInfo['basename'];
```

But I'm not sure it'll work on Windows.

2021-07-04 19:20 UTC, 50bhan commented
> @50bhan, for me, the bug is here https://github.com/nunomaduro/phpinsights/blob/master/src/Infrastructure/Repositories/LocalFilesRepository.php#L66
> 
> Could be resolved like this
> 
> ```
> $this->directoryList[] = rtrim($pathInfo['dirname'], DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . $pathInfo['basename'];
> ```
> 
> But I'm not sure it'll work on Windows.

Actually, this isn't the correct workaround. At first, I did the exact change that you've made. But the problem still remains:

<img width="828" alt="Screen Shot 2021-07-04 at 23 47 47" src="https://user-images.githubusercontent.com/36772278/124397028-c6328100-dcfc-11eb-81f0-f6d01346cd76.png">

2021-07-04 20:04 UTC, Jibbarth commented
@50bhan i think it's the expected behaviour. When we pass an absolute path, it should be used. 

But in the LocalFileRepository, it transform `/app` into `//app`

2021-07-04 20:10 UTC, 50bhan commented
@Jibbarth I was confused about it. If this is the case, the fix is easy as you said.

2021-07-04 20:14 UTC, Jibbarth commented
Great ! If I found a Windows, I'll test against

2021-07-04 20:17 UTC, 50bhan commented
@Jibbarth Thanks, it would be awesome. I updated the PR.

2021-07-11 12:52 UTC, Jibbarth approved these changes
Tested on Windows, bug was also present and now it's fixed :tada: 

Thank you @50bhan :pray:

2021-07-11 12:52 UTC, merged