add quotes around binary path
nunomaduro/phpinsights pull request #655
Opened 2023-08-17 10:19 UTC by ElRochito

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| Fixed tickets | #644

This PR adds quotes to binary path where php binary like this : 
`/Users/<username>/Library/Application Support/Herd/bin/php82`

We have a space between Application and Support and without quotes, Process stop at `/Users/<username>/Library/Application` and can't find php executable

2023-08-18 07:20 UTC, ElRochito commented
Sorry for my PR, bug was not on insights but on php-parallel-lint
I closed it

2023-09-13 06:56 UTC, ElRochito commented
@nunomaduro the suggested solution is right for you ?

2023-09-14 16:58 UTC, cmgmyr requested changes
@ElRochito thank you for your contribution, but unfortunately, the proposed solution will not work. The `Str` helper is only available when the dev dependencies are installed, which isn't always the case in production environments.

2023-09-14 17:39 UTC, ElRochito commented
@cmgmyr indee ;) I fixed it

2023-09-14 17:39 UTC, ElRochito commented
@cmgmyr indeed ;) I fixed it

2023-09-14 17:39 UTC, ElRochito commented
@cmgmyr indee ;) I fixed it

2023-09-28 02:42 UTC, cmgmyr approved these changes
Thanks!

2023-09-28 02:42 UTC, merged